### ISSUE TITLE
Headphone DAC does not play audio

### ISSUE THREAD

**Issue by sidnoway** [eqs-development/android_device_motorola_bronco#11]
I tried two generic USB-C to 3.5mm headphone DAC's and they do not show up as an audio source, instead the phone tries to charge the DAC. I cannot switch any of these settings. 
![Screenshot_20240813-033033_Settings](https://github.com/user-attachments/assets/d9bedda1-bda9-4336-b48b-cc5cf90f7538)

**Comment by Demon000** [comment]
Fake issue
